apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpro-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: dev
  template:
    metadata:
      labels:
        app: nginx
        tier: dev
    spec:
      containers:
        - name: vpro
          image: saduasar/java-webapp
          env:
            - name: demo_env
              value: "hello, welcome to k8s"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vpro-service
spec:
  selector:
    app: nginx
    tier: dev
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000  # Choose a port in the valid NodePort range (30000-32767)
